import type { Alert, ApiResponse, Asset, DashboardStats, Employee, Location, Movement, Tag } from "@/types";

const api_base_url = process.env.NEXT_PUBLIC_API_URL ?? "";
const now = new Date().toISOString();
const assets: Asset[] = [
  { asset_id: "LAP-001", asset_category_id: "CAT-LAP", asset_name: "MacBook Pro 14", manufacturer: "Apple", model: "M3 Pro", serial_number: "C02X71A1", tracking_method: "wifi_rtt", tag_id: "", employee_id: "EMP-001", location_id: "LOC-204", status: "assigned", last_seen: now, battery_level: 86, location_confidence: .94, created_at: now, updated_at: now, x_coordinate: 28, y_coordinate: 36 },
  { asset_id: "PRN-001", asset_category_id: "CAT-PRN", asset_name: "LaserJet Enterprise", manufacturer: "HP", model: "M611", serial_number: "HP2040", tracking_method: "manual", location_id: "LOC-201", status: "active", last_seen: now, location_confidence: 1, created_at: now, updated_at: now, x_coordinate: 66, y_coordinate: 24 },
  { asset_id: "MON-001", asset_category_id: "CAT-MON", asset_name: "UltraSharp 27", manufacturer: "Dell", model: "U2723QE", serial_number: "DL2719", tracking_method: "manual", employee_id: "EMP-002", location_id: "LOC-204", status: "assigned", last_seen: now, created_at: now, updated_at: now, x_coordinate: 42, y_coordinate: 48 },
  { asset_id: "CHR-001", asset_category_id: "CAT-CHR", asset_name: "Ergonomic Task Chair", manufacturer: "Herman Miller", model: "Sayl", tracking_method: "ble", tag_id: "TAG-0001", location_id: "LOC-201", status: "active", last_seen: now, battery_level: 72, location_confidence: .91, created_at: now, updated_at: now, x_coordinate: 22, y_coordinate: 65 },
  { asset_id: "CHR-002", asset_category_id: "CAT-CHR", asset_name: "Ergonomic Task Chair", manufacturer: "Herman Miller", model: "Sayl", tracking_method: "ble", tag_id: "TAG-0002", location_id: "LOC-204", status: "active", last_seen: now, battery_level: 18, location_confidence: .88, created_at: now, updated_at: now, x_coordinate: 55, y_coordinate: 72 },
  { asset_id: "TBL-001", asset_category_id: "CAT-TBL", asset_name: "Conference Table", manufacturer: "Steelcase", model: "Ology", tracking_method: "uwb", tag_id: "TAG-0003", location_id: "LOC-201", status: "active", last_seen: now, battery_level: 92, location_confidence: .97, created_at: now, updated_at: now, x_coordinate: 75, y_coordinate: 66 }
];
const employees: Employee[] = [{ employee_id: "EMP-001", employee_name: "Maya Chen", department_name: "Engineering", email: "maya.chen@assettrack.example", status: "active" }, { employee_id: "EMP-002", employee_name: "Noah Williams", department_name: "Operations", email: "noah.williams@assettrack.example", status: "active" }];
const locations: Location[] = [{ location_id: "LOC-201", building_id: "BLD-01", floor_id: "FLR-02", zone_id: "ZN-W", room_id: "RM-201", building_name: "North Campus", floor_name: "Floor 2", zone_name: "West Wing", room_name: "Collaboration Hub" }, { location_id: "LOC-204", building_id: "BLD-01", floor_id: "FLR-02", zone_id: "ZN-E", room_id: "RM-204", building_name: "North Campus", floor_name: "Floor 2", zone_name: "East Wing", room_name: "Focus Studio" }];
const movements: Movement[] = [{ movement_id: "MOV-001", asset_id: "CHR-002", previous_location_id: "LOC-204", new_location_id: "LOC-201", detection_method: "ble", location_confidence: .91, timestamp: now, triggered_by: "location_engine" }, { movement_id: "MOV-002", asset_id: "LAP-001", previous_location_id: "LOC-201", new_location_id: "LOC-204", detection_method: "wifi_rtt", location_confidence: .94, timestamp: now, triggered_by: "location_engine" }];
const alerts: Alert[] = [{ alert_id: "ALT-001", asset_id: "CHR-002", alert_type: "low_battery", severity: "medium", message: "BLE tag battery is at 18%.", status: "open", created_at: now }, { alert_id: "ALT-002", asset_id: "LAP-003", alert_type: "asset_missing", severity: "high", message: "Asset has not been seen for 24 hours.", status: "open", created_at: now }];
const tags: Tag[] = assets.filter(a => a.tag_id).map(a => ({ tag_id: a.tag_id!, tag_type: a.tracking_method === "uwb" ? "uwb" : "ble", hardware_identifier: `HW-${a.tag_id}`, asset_id: a.asset_id, battery_level: a.battery_level, last_seen: a.last_seen, status: "active", created_at: now, updated_at: now }));
async function request<T>(path: string, options?: RequestInit, fallback?: T): Promise<T> { try { const response = await fetch(`${api_base_url}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) throw new Error("Request failed"); const payload = await response.json() as ApiResponse<T>; return payload.data; } catch { if (fallback !== undefined) return fallback; throw new Error("The AssetTrack API is unavailable. Please retry."); } }
export const api = { assets: { list: () => request("/api/assets", undefined, assets), get: (asset_id: string) => request(`/api/assets/${asset_id}`, undefined, assets.find(a => a.asset_id === asset_id)), create: (data: Partial<Asset>) => request("/api/assets", { method: "POST", body: JSON.stringify(data) }), update: (asset_id: string, data: Partial<Asset>) => request(`/api/assets/${asset_id}`, { method: "PUT", body: JSON.stringify(data) }), remove: (asset_id: string) => request(`/api/assets/${asset_id}`, { method: "DELETE" }) }, employees: { list: () => request("/api/employees", undefined, employees), get: (employee_id: string) => request(`/api/employees/${employee_id}`, undefined, employees.find(e => e.employee_id === employee_id)) }, locations: { list: () => request("/api/locations", undefined, locations), get: (location_id: string) => request(`/api/locations/${location_id}`, undefined, locations.find(l => l.location_id === location_id)) }, tags: { list: () => request("/api/tags", undefined, tags) }, movements: { list: () => request("/api/movements", undefined, movements) }, alerts: { list: () => request("/api/alerts", undefined, alerts) }, dashboard: { stats: () => request<DashboardStats>("/api/dashboard/stats", undefined, { total_assets: 248, active_assets: 190, available_assets: 36, offline_assets: 8, missing_assets: 3, open_alerts: 7 }), recent_movements: () => request("/api/dashboard/recent-movements", undefined, movements), alerts: () => request("/api/dashboard/alerts", undefined, alerts) }, tracking: { location_reading: (data: unknown) => request("/api/tracking/location-reading", { method: "POST", body: JSON.stringify(data) }), movement: (data: unknown) => request("/api/tracking/movement", { method: "POST", body: JSON.stringify(data) }), get: (asset_id: string) => request(`/api/tracking/${asset_id}`) }, assistant: (message: string) => request<{ answer: string }>("/api/ai/assistant", { method: "POST", body: JSON.stringify({ message }) }, { answer: "I’m using the local development data while the API is unavailable. LAP-001 was last seen in Focus Studio, North Campus, Floor 2." }) };
