export type AssetStatus = "active" | "available" | "assigned" | "offline" | "missing" | "maintenance" | "retired";
export interface Asset { asset_id: string; asset_category_id: string; asset_name: string; manufacturer?: string; model?: string; serial_number?: string; tracking_method: "wifi_rtt" | "ble" | "uwb" | "manual" | "qr"; tag_id?: string; employee_id?: string; location_id?: string; status: AssetStatus; last_seen?: string; battery_level?: number; location_confidence?: number; created_at: string; updated_at: string; x_coordinate?: number; y_coordinate?: number; }
export interface Location { location_id: string; building_id: string; floor_id: string; zone_id?: string; room_id?: string; x_coordinate?: number; y_coordinate?: number; building_name?: string; floor_name?: string; zone_name?: string; room_name?: string; }
export interface Employee { employee_id: string; employee_name: string; department_id?: string; department_name?: string; email?: string; status?: string; }
export interface Tag { tag_id: string; tag_type: "ble" | "uwb"; hardware_identifier: string; asset_id?: string; battery_level?: number; last_seen?: string; status: string; created_at: string; updated_at: string; }
export interface Movement { movement_id: string; asset_id: string; previous_location_id?: string; new_location_id: string; detection_method: string; location_confidence?: number; timestamp: string; triggered_by?: string; notes?: string; }
export interface Alert { alert_id: string; asset_id: string; alert_type: "unexpected_movement" | "asset_missing" | "tag_offline" | "low_battery" | "location_uncertain" | "suspicious_activity"; severity: "low" | "medium" | "high" | "critical"; message: string; status: string; created_at: string; resolved_at?: string; }
export interface ApiResponse<T> { success: boolean; data: T; message: string; error_code?: string; }
export interface DashboardStats { total_assets: number; active_assets: number; available_assets: number; offline_assets: number; missing_assets: number; open_alerts: number; }
export interface LocationEvent { event: "asset_location_updated" | "asset_moved"; asset_id: string; location_id?: string; previous_location_id?: string; new_location_id?: string; x_coordinate?: number; y_coordinate?: number; location_confidence?: number; timestamp: string; }
