import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Filter, Plus, Search } from "lucide-react";
import { AppLayout } from "@/layouts/AppLayout";
import { api } from "@/services/api";
import type { Asset } from "@/types";
import { EmptyState, ErrorState, LoadingState } from "@/components/PageState";

const tone: Record<string, string> = { active: "bg-sage/40 text-primary", available: "bg-sage/40 text-primary", assigned: "bg-background text-secondary", offline: "bg-warning/15 text-warning", missing: "bg-danger/10 text-danger", maintenance: "bg-warning/15 text-warning" };
export default function Assets() { const [assets, setAssets] = useState<Asset[]>(); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [error, setError] = useState(false); const load = useCallback(() => { setError(false); api.assets.list().then(setAssets).catch(() => setError(true)); }, []); useEffect(() => { load(); }, [load]); const shown = useMemo(() => assets?.filter(a => (status === "all" || a.status === status) && (`${a.asset_id} ${a.asset_name}`.toLowerCase().includes(query.toLowerCase()))) ?? [], [assets, query, status]); return <AppLayout><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="label">Inventory management</p><h1 className="mt-1 text-3xl font-semibold">Assets</h1></div><button className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-surface"><Plus size={17}/>Register asset</button></div><div className="card rounded-xl p-4"><div className="flex flex-wrap gap-3"><label className="flex flex-1 items-center gap-2 rounded-lg border border-line bg-background px-3"><Search size={17} className="text-muted"/><input value={query} onChange={e => setQuery(e.target.value)} className="min-w-48 w-full bg-transparent py-2 outline-none" placeholder="Search asset ID or name" /></label><label className="flex items-center gap-2 rounded-lg border border-line px-3 text-sm"><Filter size={16}/><select aria-label="Filter asset status" value={status} onChange={e => setStatus(e.target.value)} className="bg-transparent py-2 outline-none"><option value="all">All statuses</option>{["active","available","assigned","offline","missing","maintenance"].map(s => <option key={s}>{s}</option>)}</select></label></div></div><div className="card mt-5 rounded-xl">{error ? <ErrorState retry={load}/> : !assets ? <LoadingState/> : shown.length === 0 ? <EmptyState title="No assets found" text="Try changing your search or filters."/> : <div className="table-wrap"><table className="w-full text-sm"><thead><tr><th>Asset ID</th><th>Asset</th><th>Category</th><th>Location</th><th>Assigned to</th><th>Tracking</th><th>Status</th><th>Last seen</th></tr></thead><tbody>{shown.map(a => <tr key={a.asset_id}><td><Link className="font-semibold text-primary hover:underline" href={`/assets/${a.asset_id}`}>{a.asset_id}</Link></td><td>{a.asset_name}</td><td>{a.asset_category_id.replace("CAT-", "")}</td><td>{a.location_id ?? "Unassigned"}</td><td>{a.employee_id ?? "—"}</td><td className="uppercase">{a.tracking_method}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${tone[a.status]}`}>{a.status}</span></td><td>{a.last_seen ? "Just now" : "—"}</td></tr>)}</tbody></table></div>}</div></AppLayout>; }
